### ISSUE TITLE
Hardware requirement for skynet ?

### ISSUE THREAD

**Issue by shooding** [jitsi/skynet#79]
Which OS is recommended ? I bought a gigabyte 3060 for this project but struggle to bring it up.

Ubuntu 20.04 (w/ CUDA from Nvidia website) is still using python 3.8 but pytorch in skynet requires python3.11. After installing python3.11 breaks many Ubuntu applications.

Or Windows is suggested ?

**Comment by saghul** [comment]
We run it on Ubuntu 20.04. Best would be to use Docker and pass through the GPU, since the image will have all dependencies installed.

**Comment by shooding** [comment]
to run with docker, need to mount models folder with -v  but

`
  File "/app/.venv/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 275, in snapshot_download
    os.makedirs(os.path.dirname(ref_path), exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  [Previous line repeated 1 more time]
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/home/me'
`
already tried chmod -R me:me /home/me/models
and chmod -R 755 /home/me/models

Wonder why do we need makedirs if the model is already mounted ?
I tried move everything to root home, then got a lot of 
filelock & try release from huggingface

**Comment by saghul** [comment]
Try with a subdirectory, not your entire home directory.

**Comment by shooding** [comment]
Forgot to pass --gpus all and "WHISPER_MODEL_PATH" should set to /models not $HOME/models because we're running within docker.

`
docker run -p 8000:8000 \
-u $(id -u):$(id -g) \
-v $HOME/models:/models \
--gpus all \
-e "BEAM_SIZE=1" \
-e WHISPER_MODEL_NAME="medium" \
-e ENABLED_MODULES="streaming_whisper" \
-e BYPASS_AUTHORIZATION=False \
-e WHISPER_MODEL_PATH="/models/streaming-whisper" \
-e "BYPASS_AUTHORIZATION=true" \
skynet:test-whisper
`

Still need to wait several min on **Attempting to acquire lock 124698291842448 ... **  and finally
`
Skynet became self aware
`
:)

**Comment by saghul** [comment]
Great work! Would you mind sending a PR?

**Comment by surajprakashchoudhary** [comment]
Hi @saghul and @shooding,

Currently, we're using the Medium Faster Whisper model for live transcription via WebSocket connections, and the Ollama 3.1 model to generate summaries. For optimal performance, we need a reliable server, as our existing setup lacks sufficient power (with at least 6 GB of available RAM required for summarization, and the capacity for fast processing of larger transcription workloads).

Our current setup uses a Digital Ocean server with 8 GB RAM, 4 vCPUs, and 160 GB SSD.(Docker-jitsi-meet and skynet are running on this server) Could you recommend the best Digital ocean server configuration for this purpose to reliably handle multiple meetings?

**Comment by saghul** [comment]
We have since moved to Ubuntu 22.04 and wun on OCI machines with A10.graphics cards.

While you can use Ollama, we recommend you use an Nvidia card of at least 24GB of VRAM, so vllm can be used, it's much faster.

**Comment by surajprakashchoudhary** [comment]
Hi @saghul, thank for your response since we're planning to use Medium-Faster-Whisper for transcription and Ollama 3.1 for summarization, do you think we’d benefit from a server with a GPU? Or would a high-performance CPU be enough to handle the load for multiple meetings?

Just trying to figure out if we need to prioritize GPU acceleration or stick with a CPU-focused setup, especially since we're only planning to host Skynet on the new server and not shift the Jitsi setup. What do you think would work best for this use case?
